#!/bin/bash
git submodule init
git submodule update

ln -s ./config/.vimrc ~/.vimrc
ln -s ./config/.vim/ ~/.vim

ln -s ./config/.bashrc ~/.bashrc
ln -s ./config/.inputrc ~/.inputrc
ln -s ./config/.bash/ ~/.bash

ln -s ./config/.tmux.conf ~/.tmux.conf
mkdir ~/.tmux/
ln -s ./config/.tmux/plugins/ ~/.tmux/plugins

ln -s ./config/.gitignore_global ~/.gitignore_global


