# tmux aliases
alias tnew='tmux new -s'

# aliases for common ls
alias ls='ls -CF --color=auto'
alias ll='ls -l --color=auto'
alias la='ls -A --color=auto'

# see: https://github.com/BenSimner/list-tree
alias lt='\lt -F --color=auto'
alias lta='\lt -AF --color=auto'
alias lg='\lt -AFg --color=auto'

alias o=zathura
